### ISSUE TITLE
better way to influence dataTable column widths

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1168]
Currently, if you're generating the table headers using the [object or string `columns` options](https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#datatablecolumnscolumns--arrayfunction--datatable), you don't have much control over the column widths.

The layout is automatic and they can move around a lot as you filter.

The best solution I've found is adding some CSS like this:

```css
#test thead tr th:nth-child(1) {
    width: 100px;
}
#test thead tr th:nth-child(2) {
    width: 50px;
}
```

Conceivably a renderlet would be less code than this but even uglier. Seems like there should be a better way of doing this!
