### ISSUE TITLE
is there any way to specify column width in dc.js datatable ?

### ISSUE THREAD

**Issue by asadmkhan** [dc-js/dc.js#1309]
is there any way to specify column width in dc.js datatable ?

**Comment by gordonwoodhull** [comment]
When any parameter of the DOM is not naturally driven by data, it makes the most sense to use CSS. You don't really need dc.js to generate this part of the layout for you.

dc.js uses the CSS class `_0` for the first column, `_1` for the second, etc.

So you can add CSS to your page like

```css
      #table td.dc-table-column._1 {
          width: 10em;
      }
```

Where `#table` specifies the id of your table.

And so on...
