### ISSUE TITLE
Issue with height calculation in base-mixin

### ISSUE THREAD

**Issue by elChapoSing** [dc-js/dc.js#1768]
https://github.com/dc-js/dc.js/blob/43296a9f6b3a40f34a4140c593f18e2e2a8cfe7a/src/base/base-mixin.js#L94

Why is the height forced to be higher than the value I have passed to it ?
When using `chart.width(null).height(null)` in a CSS grid setting, my barcharts end up being too tall for no good reason.

cf this example : https://jsfiddle.net/chapo/yj4u80fd/
```css
#test {
  display:grid;
  grid-template-columns: 1fr;
  grid-template-rows: 100px 1fr 1fr;
}
```
and yet my barchart ends up being 200px.

The issue is of course the same for width but I think there is less of a case for making very tall, very narrow graphs whereas short and wide makes sense.
